
services:
  backend:
    build:
      context: ./Movieflix-Backend
      dockerfile: Dockerfile
    container_name: movieflix-backend
    ports:
      - "5051:5051"    # HTTP port for backend API
    expose:
      - "5051" # Not strictly required, but good practice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5051
    networks:
      - movieflix-net

  frontend:
    build:
      context: ./learn-react-project
      dockerfile: Dockerfile.dev
    container_name: movieflix-frontend
    ports:
      - "5173:5173"    # Vite dev server port
    environment:
      - VITE_BASE_URL=http://localhost:5051/api   # Backend container hostname & port
    depends_on:
      - backend
    networks:
      - movieflix-net

networks:
  movieflix-net:
    driver: bridge
