
services:
  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # ✅ Vite dev server port
    stdin_open: true
    tty: true
